version: "3.8"

services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: user@email.com # Login email
      PGADMIN_DEFAULT_PASSWORD: password # Login password
    ports:
      - "5050:80" # Access pgAdmin at http://localhost:5050
    volumes:
      - pgadmin-data:/var/lib/pgadmin # Persist pgAdmin settings

volumes:
  pgadmin-data: # Store pgAdmin configuration data
