version: '3.8'

services:
  webserver:
    build:
      context: ./web-server
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /Users/datngo/Documents/repos/anythingyouwantt/localhost+2-key.pem:/etc/nginx/ssl/webserver.key
      - /Users/datngo/Documents/repos/anythingyouwantt/localhost+2.pem:/etc/nginx/ssl/webserver.crt
    # depends_on:
    #   - appserver

  # appserver:
  #   build:
  #     context: ./app-server
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - db

  # db:
  #   image: postgres:latest
  #   environment:
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    

