version: '3.8'

services:
  webserver:
    image: datngonyc/webserver:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/anythingyouwantt.com/privkey.pem:/etc/nginx/ssl/webserver.key
      - /etc/letsencrypt/live/anythingyouwantt.com/fullchain.pem:/etc/nginx/ssl/webserver.crt
    depends_on:
      - appserver

  appserver:
    image: datngonyc/appserver:latest
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 2s
      timeout: 2s
      retries: 5
      start_period: 10s
